import 'package:shared_preferences/shared_preferences.dart';

class SharedPrefs {
  static late SharedPreferences sharedPrefs;

  Future<void> init() async {
    sharedPrefs = await SharedPreferences.getInstance();
  }

  String get mylanguage => sharedPrefs.getString('language') ?? "English";
  set mylanguage(String value) {
    sharedPrefs.setString('language', value);
  }

  List<String> get mylist =>
      sharedPrefs.getStringList('mylist') ?? ["Your list is empty"];
  set mylist(List<String> value) {
    sharedPrefs.setStringList('mylist', value);
  }

  List<String> foodEn = [
    "1,3-dichloro-2-propanol",
    "1,4-dioxane",
    "2,3,7,8-tetracholordibenzo-p-dioxin",
    "2-amino-1-methyl-6-phenylimidazo[4,5-b]pyridine",
    "2-amino-3,4-dimethylimidazo[4,5-f]quinolone (meIq)",
    "2-amino-3,8-dimethylimidazo[4,5-f]quinoxalone (meIqx)",
    "2-methylimidazole",
    "3-chloro-1,2-propanediol",
    "4-methylimidazole",
    "5-methoxypsoralen",
    "acesulfame potassium",
    "acetaldehyde",
    "acrylamide",
    "acrylonitrile",
    "aflatoxins",
    "agaritine d",
    "agaritine",
    "agave nectar",
    "alkaloids",
    "alkenylbenzene",
    "alkylated imidazoles",
    "aluminum",
    "amino-3-methylimidazo[4,5-f]quinoline",
    "annatto",
    "anti-foaming agent",
    "aristolochic acid",
    "arsenic",
    "artificial color",
    "artificial flavor",
    "aspartame",
    "aspergillus flavus",
    "azodicarbonamide",
    "benz[a]anthracene",
    "benzene",
    "benzo[a]pyrene",
    "benzo[b}fluoranthene",
    "benzophenone",
    "bha",
    "bht",
    "bisphenol a",
    "bisphenols",
    "bixin",
    "bleached starch",
    "blue #1",
    "blue #2",
    "blue 1",
    "blue 2",
    "blue",
    "bpa",
    "bracken fern",
    "brominated vegetable oil",
    "brown ht",
    "butane",
    "butylated hydroxyanisole",
    "butylated hydroxytoluene",
    "bvo",
    "cadmium",
    "camauba wax",
    "canola oil",
    "canola",
    "caramel color ",
    "caramel coloring",
    "carnuba wax",
    "carrageenan (native) d",
    "carrageenan",
    "chlorate (sodium salt) d",
    "chloride",
    "chlorine dioxide",
    "chloropropanols",
    "citrus red #1",
    "citrus red #2",
    "citrus red",
    "corn",
    "corn oil",
    "cottonseed",
    "cottonseed oil",
    "coumarin",
    "crotonaldehyde",
    "cycasin",
    "daminozide",
    "dbp",
    "ddt",
    "dep",
    "dextrose",
    "di(2-ethylhexyl) phthalate",
    "dibutylphthalate",
    "dichlorodiphenyltrichloroethane",
    "diethylphthalate",
    "dimethyl silicone",
    "dioxins",
    "disodium guanylate",
    "disodium inosinate",
    "d-limonene",
    "enriched flour",
    "equal",
    "erythritol",
    "estragole",
    "ethyl carbamate",
    "ethylene oxide",
    "eugenol d",
    "flumequine",
    "fumonisin b1",
    "fumonisins",
    "furan",
    "furfural d",
    "fusarin c",
    "fusarium moniliforme",
    "genistein d",
    "grapeseed oil",
    "green #3",
    "green 3",
    "green",
    "guar gum",
    "hepatocellular carcinoma",
    "heterocyclic",
    "hexenal",
    "hfcs",
    "high fructose corn syrup",
    "hydroquinone",
    "iarc",
    "isatidine d",
    "isobutane",
    "lasiocarpine",
    "lead",
    "magnesium sulphate",
    "malondialdehyde",
    "maltodextrin",
    "maté",
    "meiq",
    "meiqx",
    "mercury",
    "methoxsalen",
    "methyl eugenol",
    "methyl isobutyl ketone",
    "methylazoxymethanol",
    "methylene",
    "monocrotaline",
    "monosodium glutamate",
    "natural flavor ",
    "nitrosamides",
    "nitrosamines",
    "nitrous oxide",
    "n-methyl-n-formylhydrazine d",
    "n-nitroso",
    "n-nitrosodiethanolamine",
    "n-nitrosodimethylamine",
    "norbixin",
    "nutraSweet",
    "ochratoxin",
    "octafluorocyclobutane",
    "olestra",
    "orange b",
    "orange",
    "p,p0dichlorodiphenyltrichloroethane",
    "pahs",
    "palm oil",
    "paraben",
    "paraquat",
    "patulin",
    "pbcs",
    "peanut oil",
    "perchlorate",
    "perfluoroalkyl",
    "pfas",
    "phlp",
    "phthalates",
    "plastics",
    "polyamides",
    "polycyclic aromatic hydrocarbons",
    "polyesters",
    "polyfluoroalkyl",
    "polymeric",
    "polyolefins",
    "polysorbate 60",
    "polystyrene",
    "potasium sorbet"
        "potassium benzoate",
    "potassium bromate",
    "prepallants",
    "propane",
    "propellant",
    "propyl gallate",
    "propyl paraben",
    "propylene glycol",
    "psoralen",
    "ptaquiloside",
    "pulegone",
    "pyrrolizidine",
    "quercetin",
    "ractopamine",
    "rbgh",
    "recombinant bovine growth hormone",
    "red #2",
    "red #3",
    "red #40",
    "red 2",
    "red 3",
    "red 40",
    "red",
    "retrorsine d",
    "rice bran oil",
    "riddelliine",
    "saccharin",
    "safflower",
    "safflower oil",
    "safrole",
    "senkirkine d",
    "sesame oil",
    "sodium benzoate",
    "sodium bisulfate",
    "sodium carboxymethyl cellulose",
    "sodium erythorbate",
    "sodium nitrates",
    "sodium nitrites",
    "sodium saccharin d",
    "sorbitol",
    "soy lecithin",
    "soybean oil",
    "splenda",
    "styrene",
    "sucralose",
    "sugartwin",
    "sunflower",
    "sunflower oil",
    "sweet'n low",
    "symphytine d",
    "tartrazine",
    "tbhq",
    "tcdd",
    "tert-butylhydroquinone",
    "titanium dioxide",
    "trans,trans-2,4-hexadienal",
    "trichloroethylene",
    "urethane",
    "vanillin",
    "vinyl chloride",
    "xanthan gum",
    "yeast extract ",
    "yellow #5",
    "yellow #6",
    "yellow 5",
    "yellow 6",
    "yellow",
    "zearalenone d",
    "α,β-aldehydes",
    "β-myrcene",
  ];

  List<String> foodSe = [
    "1,3-diklor-2-propanol",
    "1,4-dioxan",
    "2,3,7,8-tetraklordibenso-p-dioxin",
    "2-amino-1-metyl-6-fenylimidazo[4,5-b]pyridin",
    "2-amino-3,4-dimetylimidazo[4,5-f]kinolon (meIq)",
    "2-amino-3,8-dimetylimidazo[4,5-f]kinoxalon (meIqx)",
    "2-metylimidazol",
    "3-klor-1,2-propandiol",
    "4-metylimidazol",
    "5-metoxipsoralen",
    "acesulfam kalium",
    "acetaldehyd",
    "akrylamid",
    "akrylnitril",
    "aflatoxiner",
    "agaritin d",
    "agaritin",
    "agave nektar",
    "alkaloider",
    "alkenylbensen",
    "alkylerade imidazoler",
    "aluminium",
    "amino-3-metylimidazo[4,5-f]kinolin",
    "annatto",
    "skumdämpande medel",
    "aristolochic acid",
    "arsenik",
    "konstgjord färg",
    "konstgjord smak",
    "aspartam",
    "aspergillus flavus",
    "azodikarbonamid",
    "bens[a]antracen",
    "bensen",
    "benso[a]pyren",
    "benso[b}fluoranten",
    "bensofenon",
    "bha",
    "bht",
    "bisfenol a",
    "bisfenoler",
    "bixin",
    "blekt stärkelse",
    "blå #1",
    "blå #2",
    "blå 1",
    "blå 2",
    "blå",
    "bpa",
    "bracken fern",
    "bromerad vegetabilisk olja",
    "brun ht",
    "butan",
    "butylerad hydroxyanisol",
    "butylerad hydroxitoluen",
    "bvo",
    "kadmium",
    "camaubavax",
    "canolaolja",
    "raps",
    "karamellfärg",
    "karamellfärg",
    "karnubavax",
    "karragenan (infödd) d",
    "karragenan",
    "klorat (natriumsalt) d",
    "klorid",
    "klordioxid",
    "klorpropanoler",
    "citrusröd #1",
    "citrusröd #2",
    "citrusröd",
    "majs",
    "majsolja",
    "bomullsfrö",
    "bomullsfröolja",
    "kumarin",
    "krotonaldehyd",
    "cycasin",
    "daminozid",
    "dbp",
    "ddt",
    "dep",
    "glukos",
    "di(2-etylhexyl)ftalat",
    "dibutylftalat",
    "diklordifenyltrikloretan",
    "dietylftalat",
    "dimetylsilikon",
    "dioxiner",
    "dinatriumguanylat",
    "dinatriuminosinat",
    "d-limonen",
    "berikat mjöl",
    "likvärdig",
    "erytritol",
    "estragol",
    "etylkarbamat",
    "etylenoxid",
    "eugenol d",
    "flumequine",
    "fumonisin b1",
    "fumonisiner",
    "furan",
    "furfural d",
    "fusarin c",
    "fusarium moniliforme",
    "genistein d",
    "druvkärneolja",
    "grön #3",
    "grön 3",
    "grön",
    "guargummi",
    "hepatocellulärt karcinom",
    "heterocyklisk",
    "hexenal",
    "hfcs",
    "hög fruktos majssirap",
    "hydrokinon",
    "iarc",
    "isatidin d",
    "isobutan",
    "lasiokarpin",
    "leda",
    "magnesiumsulfat",
    "malondialdehyd",
    "maltodextrin",
    "para",
    "meiq",
    "meiqx",
    "kvicksilver",
    "metoxsalen",
    "metyl eugenol",
    "metylisobutylketon",
    "metylazoximetanol",
    "metylen",
    "monokrotalin",
    "mononatriumglutamat",
    "naturlig smak",
    "nitrosamider",
    "nitrosaminer",
    "lustgas",
    "n-metyl-n-formylhydrazin d",
    "n-nitroso",
    "n-nitrosodietanolamin",
    "n-nitrosodimetylamin",
    "norbixin",
    "nutraSweet",
    "okratoxin",
    "oktafluorcyklobutan",
    "olestra",
    "orange b",
    "orange",
    "p,p0diklordifenyltrikloretan",
    "pahs",
    "palmolja",
    "paraben",
    "paraquat",
    "patulin",
    "pbcs",
    "jordnötsolja",
    "perklorat",
    "perfluoralkyl",
    "pfas",
    "phlp",
    "ftalater",
    "plast",
    "polyamider",
    "polycykliska aromatiska kolväten",
    "polyestrar",
    "polyfluoralkyl",
    "polymer",
    "polyolefiner",
    "polysorbat 60",
    "polystyren",
    "kaliumsorbet"
        "kaliumbensoat",
    "kaliumbromat",
    "prepallanter",
    "propan",
    "drivmedel",
    "propylgallat",
    "propylparaben",
    "propylenglykol",
    "psoralen",
    "ptaquilosid",
    "pulegone",
    "pyrrolizidin",
    "quercetin",
    "raktopamin",
    "rbgh",
    "rekombinant bovint tillväxthormon",
    "röd 2",
    "röd #3",
    "röd #40",
    "röd 2",
    "röd 3",
    "röd 40",
    "röd",
    "retrorsine d",
    "riskliolja",
    "riddelliine",
    "sackarin",
    "safflor",
    "safflorolja",
    "safrole",
    "senkirkine d",
    "sesamolja",
    "natriumbensoat",
    "natriumbisulfat",
    "natriumkarboximetylcellulosa",
    "natriumerytorbat",
    "natriumnitrat",
    "natriumnitrit",
    "natriumsackarin d",
    "sorbitol",
    "soja lecitin",
    "sojabönsolja",
    "splenda",
    "styren",
    "sukralos",
    "sugartwin",
    "solros",
    "solrosolja",
    "sweet'n low",
    "symfytin d",
    "tartrazin",
    "tbhq",
    "tcdd",
    "tert-butylhydrokinon",
    "titandioxid",
    "trans,trans-2,4-hexadienal",
    "trikloretylen",
    "uretan",
    "vanillin",
    "vinylklorid",
    "xantangummi",
    "jästextrakt ",
    "gul #5",
    "gul #6",
    "gul 5",
    "gul 6",
    "gul",
    "zearalenone d",
    "α,β-aldehyder",
    "β-myrcene",
  ];

  List<String> foodEs = [
    "1,3-dicloro-2-propanol",
    "1,4-dioxano",
    "2,3,7,8-tetracholordibenzo-p-dioxina",
    "2-amino-1-metil-6-fenilimidazo[4,5-b]piridina",
    "2-amino-3,4-dimetilimidazo[4,5-f]quinolona (meIq)",
    "2-amino-3,8-dimetilimidazo[4,5-f]quinoxalona (meIqx)",
    "2-metilimidazol",
    "3-cloro-1,2-propanodiol",
    "4-metilimidazol",
    "5-metoxipsoraleno",
    "acesulfamo de potasio",
    "acetaldehído",
    "acrilamida",
    "acrilonitrilo",
    "aflatoxinas",
    "agaritina d",
    "agaritina",
    "néctar de agave",
    "alcaloides",
    "alquenilbenceno",
    "imidazoles alquilados",
    "aluminio",
    "amino-3-metilimidazo[4,5-f]quinolina",
    "anato",
    "agente antiespumante",
    "ácido aristolóquico",
    "arsénico",
    "color artificial",
    "sabor artificial",
    "aspartamo",
    "aspergillus flavus",
    "azodicarbonamida",
    "benz[a]antraceno",
    "benceno",
    "benzo[a]pireno",
    "benzo[b}fluoranteno",
    "benzofenona",
    "bha",
    "bht",
    "el bisfenol a",
    "bisfenoles",
    "bixina",
    "almidón blanqueado",
    "azul #1",
    "azul #2",
    "azul 1",
    "azul 2",
    "azul",
    "bpa",
    "helecho helecho",
    "aceite vegetal bromado",
    "marrón ht",
    "butano",
    "hidroxianisol butilado",
    "hidroxitolueno butilado",
    "bvo",
    "cadmio",
    "cera de camauba",
    "aceite de canola",
    "canola",
    "color caramelo ",
    "colorante caramelo",
    "cera de carnuba",
    "carragenina (nativa) d",
    "carragenina",
    "clorato (sal de sodio) d",
    "cloruro",
    "dioxido de cloro",
    "cloropropanoles",
    "rojo cítrico #1",
    "rojo cítrico #2",
    "rojo cítrico",
    "maíz",
    "aceite de maíz",
    "semilla de algodón",
    "aceite de algodón",
    "cumarina",
    "crotonaldehído",
    "cicasina",
    "daminozida",
    "dbp",
    "ddt",
    "profundidad",
    "dextrosa",
    "ftalato de di (2-etilhexilo)",
    "ftalato de dibutilo",
    "diclorodifeniltricloroetano",
    "dietilftalato",
    "dimetilsilicona",
    "dioxinas",
    "guanilato de disodio",
    "inosinato disódico",
    "d-limoneno",
    "harina enriquecida",
    "igual",
    "eritritol",
    "estragol",
    "carbamato de etilo",
    "óxido de etileno",
    "eugenol d",
    "flumequina",
    "fumonisina b1",
    "fumonisinas",
    "furano",
    "furfural d",
    "fusarina c",
    "fusarium moniliforme",
    "genisteína d",
    "aceite de semilla de uva",
    "verde #3",
    "verde 3",
    "verde",
    "goma de guar",
    "carcinoma hepatocelular",
    "heterocíclico",
    "hexenal",
    "hfcs",
    "jarabe de maíz con alta fructuosa",
    "hidroquinona",
    "iarc",
    "isatidina d",
    "isobutano",
    "lasiocarpina",
    "dirigir",
    "sulfato de magnesio",
    "malondialdehído",
    "maltodextrina",
    "compañero",
    "meiq",
    "meiqx",
    "mercurio",
    "metoxsaleno",
    "metil eugenol",
    "metilisobutilcetona",
    "metilazoximetanol",
    "metileno",
    "monocrotalina",
    "glutamato monosódico",
    "sabor natural ",
    "nitrosamidas",
    "nitrosamines",
    "nitrous oxide",
    "n-methyl-n-formylhydrazine d",
    "n-nitroso",
    "n-nitrosodiethanolamine",
    "n-nitrosodimethylamine",
    "norbixin",
    "nutraSweet",
    "ochratoxin",
    "octafluorocyclobutane",
    "olestra",
    "orange b",
    "orange",
    "p,p0dichlorodiphenyltrichloroethane",
    "pahs",
    "palm oil",
    "paraben",
    "paraquat",
    "patulin",
    "pbcs",
    "peanut oil",
    "perchlorate",
    "perfluoroalkyl",
    "pfas",
    "phlp",
    "phthalates",
    "plastics",
    "polyamides",
    "polycyclic aromatic hydrocarbons",
    "polyesters",
    "polyfluoroalkyl",
    "polymeric",
    "polyolefins",
    "polysorbate 60",
    "polystyrene",
    "potasium sorbet"
        "potassium benzoate",
    "potassium bromate",
    "prepallants",
    "propane",
    "propellant",
    "propyl gallate",
    "propyl paraben",
    "propylene glycol",
    "psoralen",
    "ptaquiloside",
    "pulegone",
    "pyrrolizidine",
    "quercetin",
    "ractopamine",
    "rbgh",
    "recombinant bovine growth hormone",
    "red #2",
    "red #3",
    "red #40",
    "red 2",
    "red 3",
    "red 40",
    "red",
    "retrorsine d",
    "rice bran oil",
    "riddelliine",
    "saccharin",
    "safflower",
    "safflower oil",
    "safrole",
    "senkirkine d",
    "sesame oil",
    "sodium benzoate",
    "sodium bisulfate",
    "sodium carboxymethyl cellulose",
    "sodium erythorbate",
    "sodium nitrates",
    "sodium nitrites",
    "sodium saccharin d",
    "sorbitol",
    "soy lecithin",
    "soybean oil",
    "splenda",
    "styrene",
    "sucralose",
    "sugartwin",
    "sunflower",
    "sunflower oil",
    "sweet'n low",
    "symphytine d",
    "tartrazine",
    "tbhq",
    "tcdd",
    "tert-butylhydroquinone",
    "titanium dioxide",
    "trans,trans-2,4-hexadienal",
    "trichloroethylene",
    "urethane",
    "vanillin",
    "vinyl chloride",
    "xanthan gum",
    "yeast extract ",
    "yellow #5",
    "yellow #6",
    "yellow 5",
    "yellow 6",
    "yellow",
    "zearalenone d",
    "α,β-aldehydes",
    "β-myrcene",
  ];
}
